import React, { useState } from 'react';
import { Copy, Check, AlertTriangle, Download, Printer } from 'lucide-react';
import { useToast } from '../context/ToastContext';
import { copyToClipboard, triggerHapticFeedback } from '../utils/clipboard';

interface RecoveryKeyDisplayProps {
  recoveryKey: string;
  onConfirm: () => void;
}

const RecoveryKeyDisplay: React.FC<RecoveryKeyDisplayProps> = ({ recoveryKey, onConfirm }) => {
  const [copied, setCopied] = useState(false);
  const [confirmed, setConfirmed] = useState(false);
  const { success } = useToast();

  const handleCopy = async () => {
    const copySuccess = await copyToClipboard(recoveryKey);
    
    if (copySuccess) {
      setCopied(true);
      success('✓ Recovery key copied to clipboard');
      setTimeout(() => setCopied(false), 3000);
      triggerHapticFeedback();
    } else {
      success('❌ Copy failed. Please use Download or Print instead.');
    }
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>FileSafe Recovery Key</title>
            <style>
              body {
                font-family: system-ui, -apple-system, sans-serif;
                padding: 40px;
                max-width: 600px;
                margin: 0 auto;
              }
              h1 { color: #4F46E5; }
              .key {
                font-size: 24px;
                font-weight: bold;
                letter-spacing: 2px;
                padding: 20px;
                background: #f3f4f6;
                border: 2px solid #4F46E5;
                border-radius: 8px;
                text-align: center;
                margin: 20px 0;
              }
              .warning {
                background: #FEF3C7;
                padding: 15px;
                border-left: 4px solid #F59E0B;
                margin: 20px 0;
              }
            </style>
          </head>
          <body>
            <h1>FileSafe Recovery Key</h1>
            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
            <div class="key">${recoveryKey}</div>
            <div class="warning">
              <strong>⚠️ IMPORTANT:</strong>
              <ul>
                <li>Keep this key in a safe place</li>
                <li>You'll need it if you forget your PIN</li>
                <li>Anyone with this key can reset your PIN</li>
                <li>Do not share this key with anyone</li>
              </ul>
            </div>
            <p><em>Generated by FileSafe - Personal Document Assistant</em></p>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
    success('✓ Opening print dialog');
  };

  const handleDownload = () => {
    const content = `FileSafe Recovery Key
Date: ${new Date().toLocaleDateString()}

Your Recovery Key:
${recoveryKey}

⚠️ IMPORTANT INSTRUCTIONS:
• Keep this key in a safe place
• You'll need it if you forget your PIN
• Anyone with this key can reset your PIN
• Do not share this key with anyone
• Store this file securely (not in FileSafe)

Generated by FileSafe - Personal Document Assistant
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `filesafe-recovery-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    success('✓ Recovery key downloaded');
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-500 to-primary-700 flex flex-col items-center justify-center p-6">
      <div className="w-full max-w-md">
        {/* Header */}
        <div className="text-center mb-6">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-yellow-400 rounded-full shadow-lg mb-4">
            <AlertTriangle className="text-yellow-900" size={32} />
          </div>
          <h1 className="text-2xl font-bold text-white mb-2">Save Your Recovery Key</h1>
          <p className="text-primary-100">
            This is the ONLY way to reset your PIN if you forget it
          </p>
        </div>

        {/* Recovery Key Card */}
        <div className="bg-white rounded-3xl shadow-2xl p-6 mb-4">
          <div className="mb-4">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Your Recovery Key:
            </label>
            <div className="relative">
              <div className="bg-gray-100 border-2 border-primary-500 rounded-xl p-4 text-center">
                <p className="text-2xl font-mono font-bold text-gray-900 tracking-wider break-all">
                  {recoveryKey}
                </p>
              </div>
              <button
                onClick={handleCopy}
                className={`absolute top-2 right-2 p-2 rounded-lg transition-colors ${
                  copied
                    ? 'bg-green-100 text-green-600'
                    : 'bg-white text-gray-600 hover:bg-gray-50'
                }`}
              >
                {copied ? <Check size={20} /> : <Copy size={20} />}
              </button>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="grid grid-cols-3 gap-2 mb-4">
            <button
              onClick={handleCopy}
              className="flex flex-col items-center gap-1 p-3 rounded-lg bg-gray-50 hover:bg-gray-100 active:bg-gray-200 transition-colors"
            >
              <Copy size={20} className="text-primary-600" />
              <span className="text-xs font-medium text-gray-700">Copy</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex flex-col items-center gap-1 p-3 rounded-lg bg-gray-50 hover:bg-gray-100 active:bg-gray-200 transition-colors"
            >
              <Printer size={20} className="text-primary-600" />
              <span className="text-xs font-medium text-gray-700">Print</span>
            </button>

            <button
              onClick={handleDownload}
              className="flex flex-col items-center gap-1 p-3 rounded-lg bg-gray-50 hover:bg-gray-100 active:bg-gray-200 transition-colors"
            >
              <Download size={20} className="text-primary-600" />
              <span className="text-xs font-medium text-gray-700">Download</span>
            </button>
          </div>

          {/* Warning Box */}
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-4">
            <p className="text-sm font-semibold text-yellow-900 mb-2">⚠️ Critical Instructions:</p>
            <ul className="text-xs text-yellow-800 space-y-1">
              <li>✓ Write this down on paper</li>
              <li>✓ Store in a safe place (safe, lockbox)</li>
              <li>✓ Take a photo and store securely offline</li>
              <li>✗ Do NOT save only in FileSafe</li>
              <li>✗ Do NOT share with anyone</li>
            </ul>
          </div>

          {/* Confirmation Checkbox */}
          <label className="flex items-start gap-3 cursor-pointer">
            <input
              type="checkbox"
              checked={confirmed}
              onChange={(e) => setConfirmed(e.target.checked)}
              className="mt-1 w-5 h-5 text-primary-600 rounded focus:ring-2 focus:ring-primary-500"
            />
            <span className="text-sm text-gray-700">
              I have saved my recovery key in a safe place. I understand that without it, I cannot
              reset my PIN if I forget it.
            </span>
          </label>
        </div>

        {/* Continue Button */}
        <button
          onClick={onConfirm}
          disabled={!confirmed}
          className={`w-full py-4 rounded-xl font-semibold text-lg transition-all ${
            confirmed
              ? 'bg-white text-primary-600 hover:bg-primary-50 shadow-lg'
              : 'bg-white/30 text-white/50 cursor-not-allowed'
          }`}
        >
          {confirmed ? 'Continue to FileSafe' : 'Please confirm you saved the key'}
        </button>

        {/* Additional Warning */}
        <p className="text-center text-primary-100 text-xs mt-4">
          Losing this key means permanent lockout if you forget your PIN
        </p>
      </div>
    </div>
  );
};

export default RecoveryKeyDisplay;
